In [3]:
import numpy as np

# 1. 배열 생성,연습

In [26]:
a = np.arange(2,25,2)
print(a)

[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [7]:
a[2:5] = -20
print(a)

[  1   3 -20 -20 -20  11  13  15  17  19  21  23]


In [9]:
b = a.reshape(3,4)
print(b)

[[  1   3 -20 -20]
 [-20  11  13  15]
 [ 17  19  21  23]]


In [12]:
a = a.reshape(2,6)
print(c)

[[  1   3 -20 -20 -20  11]
 [ 13  15  17  19  21  23]]


In [22]:
a1 = a[0]
print(a1)

[  1   3 -20 -20 -20  11]


In [26]:
a1[...] = 0
print(a1)

[0 0 0 0 0 0]


# 2.배열 연산, 함수 연습

## 1) 난수 생성

In [66]:
x = np.round(10 * np.random.random((3,3)))
y = np.round(10 * np.random.random((3,3)))

In [67]:
print("x : \n",x)
print("\ny : \n", y)

x : 
 [[4. 6. 2.]
 [3. 4. 4.]
 [8. 6. 1.]]

y : 
 [[ 2.  4.  6.]
 [ 5.  1.  6.]
 [10.  3.  6.]]


## 2) x의 1행 2행 출력

In [68]:
print("x의 1행 : ",x[1])
print("x의 2행 : ",x[2])

x의 1행 :  [3. 4. 4.]
x의 2행 :  [8. 6. 1.]


## 3) x의 2열 출력

In [69]:
print("x의 2열 : ",x[:,2])

x의 2열 :  [2. 4. 1.]


## 4) x의 0열 1행,2행 출력

In [70]:
print("x의 0열의 1,2행 추출 : ",x[1:,0])

x의 0열의 1,2행 추출 :  [3. 8.]


## 5) x의 1열 1행,2행 출력

In [71]:
print("x의 1열의 1,2행 추출 : ",x[1:,1])

x의 1열의 1,2행 추출 :  [4. 6.]


## 6) x의 각 행의 합 출력

In [72]:
print("x의 각 행의 합")
print("0 행 : ",np.sum(x[0]))
print("1 행 : ",np.sum(x[1]))
print("2 행 : ",np.sum(x[2]))

x의 각 행의 합
0 행 :  12.0
1 행 :  11.0
2 행 :  15.0


## 7) x의 각 열의 합 출력

In [73]:
print("x의 각 열의 합")
print("0 열 : ",np.sum(x[:,0]))
print("1 열 : ",np.sum(x[:,1]))
print("2 열 : ",np.sum(x[:,2]))

x의 각 열의 합
0 열 :  15.0
1 열 :  16.0
2 열 :  7.0


## 7) x의 각 열,행의 최대값 출력

In [74]:
print("x의 각행의 최대값, 각 열의 최대값, 출력")
print("0 행 : ",np.max(x[0]))
print("1 행 : ",np.max(x[1]))
print("2 행 : ",np.max(x[2]))
print("0 열 : ",np.max(x[:,0]))
print("1 열 : ",np.max(x[:,1]))
print("2 열 : ",np.max(x[:,2]))

x의 각행의 최대값, 각 열의 최대값, 출력
0 행 :  6.0
1 행 :  4.0
2 행 :  8.0
0 열 :  8.0
1 열 :  6.0
2 열 :  4.0


## 8) x와y의 합,곱,내적 출력

In [76]:
mat_sum = x + y
mat_mul = x * y
mat_inner = np.matmul(x,y)


print("합 : \n",mat_sum)
print("\n곱 : \n",mat_mul)
print("\n내적 : \n",mat_inner)

합 : 
 [[ 6. 10.  8.]
 [ 8.  5. 10.]
 [18.  9.  7.]]

곱 : 
 [[ 8. 24. 12.]
 [15.  4. 24.]
 [80. 18.  6.]]

내적 : 
 [[58. 28. 72.]
 [66. 28. 66.]
 [56. 41. 90.]]


# 3.배열 복사, 결합 연습

## 1) 1차원 배열 3개를 생성,행으로 결합해 y배열 생성

In [4]:
a1 = np.arange(1,4)
a2 = np.arange(10,31,10)
a3 = np.arange(100,301,100)

In [5]:
y = np.vstack([a1,a2,a3])
print(y)

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]]


## 2) y배열의 0,2열을 복사하여 y1, 1열을 복사하여 y2생성

In [21]:
# reshape 해야함 열단위의 결합
y1 = np.vstack([y[:,0],y[:,2]])
y1 = y1.T
print("Y1:\n",y1)

y2 = y[:,1].reshape(3,1)
print("\nY2:\n",y2)

Y1:
 [[  1   3]
 [ 10  30]
 [100 300]]

Y2:
 [[  2]
 [ 20]
 [200]]


## 3) y1과 y2를 결합하여 yy배열 생성

In [25]:
yy = np.vstack([y1.T,y2.T])
yy = yy.T
print("YY:\n",yy)

YY:
 [[  1   3   2]
 [ 10  30  20]
 [100 300 200]]
