# Numpy 배열 클래스의 예

In [2]:
import numpy as np

a = np.arange(15)
print("**Arrays**")
print("a=",a)
print("a.ndim=",a.ndim)
print("a.shape=",a.shape)
print("a.dtype.name=",a.dtype.name)
print("a.itemsize=",a.itemsize)
print("a.size=",a.size)
print("type(a)=",type(a))

b = a.reshape(3,5)
print("a.reshape(3,5)=",b)
print("b.ndim=",b.ndim)
print("b.shape=",b.shape)

**Arrays**
a= [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
a.ndim= 1
a.shape= (15,)
a.dtype.name= int32
a.itemsize= 4
a.size= 15
type(a)= <class 'numpy.ndarray'>
a.reshape(3,5)= [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
b.ndim= 2
b.shape= (3, 5)


# 배열 생성

In [6]:
print("**Array creation**")
f1 = np.arange(0,2,0.4)
print("f1:",f1)
f2 = np.linspace(0,2,6)
print("f2:",f2)
z = np.zeros((2,2))
print("z:",z)
o = np.ones((1,2))
print("o:",o)
c = np.full((2,2),7)
print("c:",c)
e = np.eye(2)
print("e:",e)
r = np.random.random((2,2))
print("r:",r)
r2 = np.round(5*np.random.random((3,4)))
print("r2:",r2)
a1 = np.array([2,3,4])
print("a1:",a1)
a2 = np.array([[1,2,3],[5,6,7]])
print("a2:",a2)
v1 = [33,44,55,66]
print("v1:",v1)
v2 = []
for v in v1:
    v2.append(2*v)
    
print("v2:",v2)

**Array creation**
f1: [0.  0.4 0.8 1.2 1.6]
f2: [0.  0.4 0.8 1.2 1.6 2. ]
z: [[0. 0.]
 [0. 0.]]
o: [[1. 1.]]
c: [[7 7]
 [7 7]]
e: [[1. 0.]
 [0. 1.]]
r: [[0.98594495 0.78076253]
 [0.43055078 0.22163446]]
r2: [[4. 0. 1. 4.]
 [3. 1. 2. 1.]
 [4. 3. 3. 4.]]
a1: [2 3 4]
a2: [[1 2 3]
 [5 6 7]]
v1: [33, 44, 55, 66]
v2: [66, 88, 110, 132]


# 배열 연산,함수

In [8]:
print("**Array operation**")
a = np.arange(5)
b = np.array([5,6,7,8,9])
print("b = ",b)
print("a + 2 = ",a+2)
print("a ** 2 = ",a**2)
print("a < 2 = ",a<2)
print("a + b = ",a+b)
print("max(a) = ",max(a))
print("sum(a) = ",sum(b))
print("a.sum() = ",a.sum())

m1 = np.array([[1,2],[1,0]])
m2 = np.array([[1,2],[3,2]])
print("m1 = ",m1)
print("m2 = ",m2)
print("m1.sum(axis=0) = ",m1.sum(axis=0))
print("m1.sum(axis=1) = ",m1.sum(axis=1))
print("m1 + m2 = ",m1+m2)
print("m1 * m2 = ",m1*m2)
print("m1 @ m2 = ",m1 @ m2)
print("m1.dot(m2) = ",m1.dot(m2))
print("m1 < 2 = ",m1<2)

B = np.arange(3)
print("B=",B)
print("np.exp(B)=",np.exp(B))
print("np.sqrt(B)=",np.sqrt(B))

C = np.array([2.,-1.,4.])
print("C=",C)
print("np.add(B,C)=",np.add(B,C))

**Array operation**
b =  [5 6 7 8 9]
a + 2 =  [2 3 4 5 6]
a ** 2 =  [ 0  1  4  9 16]
a < 2 =  [ True  True False False False]
a + b =  [ 5  7  9 11 13]
max(a) =  4
sum(a) =  35
a.sum() =  10
m1 =  [[1 2]
 [1 0]]
m2 =  [[1 2]
 [3 2]]
m1.sum(axis=0) =  [2 2]
m1.sum(axis=1) =  [3 1]
m1 + m2 =  [[2 4]
 [4 2]]
m1 * m2 =  [[1 4]
 [3 0]]
m1 @ m2 =  [[7 6]
 [1 2]]
m1.dot(m2) =  [[7 6]
 [1 2]]
m1 < 2 =  [[ True False]
 [ True  True]]
B= [0 1 2]
np.exp(B)= [1.         2.71828183 7.3890561 ]
np.sqrt(B)= [0.         1.         1.41421356]
C= [ 2. -1.  4.]
np.add(B,C)= [2. 0. 6.]


# indexing slicing assigning

In [9]:
print("**Array indexing Slicing**")
a = np.arange(5)
print("a = ",a)
print("a[0] = ",a[0])
a1 = a[2:4]
print("a[2:4] = ",a1)
a2 = a[:2]
print("a[:2] = ",a2)
a3 = a[-1]
print("a[-1] = ",a3)
a4 = a[1:4:2]
print("a[1:4:2] = ",a4)

print("** index arrays **")
i = [1,3,4]
a[i]
print("type(a)=",type(a))
print("i = ",i)
print("a[i] = ",a[i])

print("** mask index arrays **")
f = [True,False,True,True,False]
print("f = ",f)
print("a[f] = ",a[f])
print("** Assigning values **")
a[0] = 100
a[1:3] = -2
print("a = ", a)
i = a[1:3]
i[1:3] = 99
print("a = ", a)
print("i = ", i)

**Array indexing Slicing**
a =  [0 1 2 3 4]
a[0] =  0
a[2:4] =  [2 3]
a[:2] =  [0 1]
a[-1] =  4
a[1:4:2] =  [1 3]
** index arrays **
type(a)= <class 'numpy.ndarray'>
i =  [1, 3, 4]
a[i] =  [1 3 4]
** mask index arrays **
f =  [True, False, True, True, False]
a[f] =  [0 2 3]
** Assigning values **
a =  [100  -2  -2   3   4]
a =  [100  -2  99   3   4]
i =  [-2 99]


# 2차원 indexing slicing

In [11]:
print("** 2차원 indexing, slicing, index arrays **")
a2 = np.array([[1,2,3,4],[10,20,30,40],[6,7,8,9]])
print("a2 = ",a2)
print("a2[1,2] = ",a2[1,2])
print("a2[:,1] = ",a2[:,1])
print("a2[1:3,2:3] = ",a2[1:3,2:3])
print("a2[1:2,:] = ",a2[1:2,:])
print("a2[-1] = ",a2[-1])
print("a2[1,:] = ",a2[1,:])
print("a2[1, ...] = ",a2[1,...])

m = a2 < 10
print("m = ",m)
print("a2[m] = ",a2[m])

print("** 2차원 iterator **")
for r in a2:
    print(r)
    
for e in a2.flat:
    print(e)

** 2차원 indexing, slicing, index arrays **
a2 =  [[ 1  2  3  4]
 [10 20 30 40]
 [ 6  7  8  9]]
a2[1,2] =  30
a2[:,1] =  [ 2 20  7]
a2[1:3,2:3] =  [[30]
 [ 8]]
a2[1:2,:] =  [[10 20 30 40]]
a2[-1] =  [6 7 8 9]
a2[1,:] =  [10 20 30 40]
a2[1, ...] =  [10 20 30 40]
m =  [[ True  True  True  True]
 [False False False False]
 [ True  True  True  True]]
a2[m] =  [1 2 3 4 6 7 8 9]
** 2차원 iterator **
[1 2 3 4]
[10 20 30 40]
[6 7 8 9]
1
2
3
4
10
20
30
40
6
7
8
9


# Shape Manipulation

In [12]:
a = np.floor(10*np.random.random((3,4)))
print("a=",a)
print("a.shape",a.shape)
b = a.ravel()
print("a.ravel()=",b)
c = a.reshape(6,2)
print("a.reshape(6,2) = ",c)
at = a.T
print("a.T) = ",at)
print("a.a.T.shape = ", a.T.shape)
d = a.resize((2,6))
print("a.reshape(2,6) = ",a)
print("a.reshape(2,6) = ",d)
e = a.reshape(3,-1)
print("a.reshape(3,-1) = ",e)

a= [[7. 4. 4. 0.]
 [9. 0. 7. 2.]
 [4. 4. 9. 5.]]
a.shape (3, 4)
a.ravel()= [7. 4. 4. 0. 9. 0. 7. 2. 4. 4. 9. 5.]
a.reshape(6,2) =  [[7. 4.]
 [4. 0.]
 [9. 0.]
 [7. 2.]
 [4. 4.]
 [9. 5.]]
a.T) =  [[7. 9. 4.]
 [4. 0. 4.]
 [4. 7. 9.]
 [0. 2. 5.]]
a.a.T.shape =  (4, 3)
a.reshape(2,6) =  [[7. 4. 4. 0. 9. 0.]
 [7. 2. 4. 4. 9. 5.]]
a.reshape(2,6) =  None
a.reshape(3,-1) =  [[7. 4. 4. 0.]
 [9. 0. 7. 2.]
 [4. 4. 9. 5.]]


# View, Shallow copy/deep copy

In [13]:
a = np.arange(12)
b = a
print("a=",a)
print("b=",b)
print("b is a",b is a)
b.shape = 3,4
print("b.shape=",b.shape)
print("a.shape=",a.shape)
print("a=",a)
print("b=",b)

c = a.view()
print("c=",c)
print("c is a",c is a)
print("c.base is a=",c.base is a)
c.shape = 2,6
c[0,4] = 1234
print("c.shape=",c.shape)
print("a.shape=",a.shape)
print("c=",c)
print("a=",a)

d = a.copy()
print("d=",d)
print("d is a",d is a)
print("d.base is a",d.base is a)
d[0,0] = 99
print("d=",d)
print("a=",a)

a= [ 0  1  2  3  4  5  6  7  8  9 10 11]
b= [ 0  1  2  3  4  5  6  7  8  9 10 11]
b is a True
b.shape= (3, 4)
a.shape= (3, 4)
a= [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b= [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
c= [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
c is a False
c.base is a= True
c.shape= (2, 6)
a.shape= (3, 4)
c= [[   0    1    2    3 1234    5]
 [   6    7    8    9   10   11]]
a= [[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
d= [[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
d is a False
d.base is a False
d= [[  99    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
a= [[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]


# vector stacking 벡터 결합

In [15]:
x = np.arange(0,10,2)
y = np.arange(5)
m = np.vstack([x,y])

xy = np.hstack([x,y])

print("x=",x)
print("y=",y)
print("m=",m)
print("xy=",xy)

x= [0 2 4 6 8]
y= [0 1 2 3 4]
m= [[0 2 4 6 8]
 [0 1 2 3 4]]
xy= [0 2 4 6 8 0 1 2 3 4]
